# Marble-Sorter
PLTW Engineering project - due on 1-26-17
#pragma config(Sensor, in1,    line,           sensorLineFollower)
#pragma config(Sensor, dgtl2,  button,         sensorTouch)
#pragma config(Sensor, dgtl3,  encode,         sensorQuadEncoder)
#pragma config(Motor,  port2,           spinner,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           spinner1,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int threshold = 1050;
int threshold1 = 628;

task main()
{
	{
		{
  if(SensorValue(line) >= threshold)
{

}
  motor(spinner) = 127;
  wait1Msec(50);
}
motor(spinner)= 0;
}
}
